// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqecoplqznbfxwumxaew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZWNvcGxxem5iZnh3dW14YWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzgyMDYsImV4cCI6MjA3MTI1NDIwNn0.7Z4zmyuqTByGcplVH11qTRQK7xCVdOucc7G_OJ0ynFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});